module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        /* ── Surface / Background tokens → CSS variables (auto-theme) ── */
        "background":                  "var(--tw-c-bg)",
        "on-background":               "var(--tw-c-on-bg)",
        "surface":                     "var(--tw-c-surface)",
        "surface-dim":                 "var(--tw-c-surface-dim)",
        "surface-bright":              "var(--tw-c-surface-bright)",
        "surface-container-lowest":    "var(--tw-c-container-lowest)",
        "surface-container-low":       "var(--tw-c-container-low)",
        "surface-container":           "var(--tw-c-container)",
        "surface-container-high":      "var(--tw-c-container-high)",
        "surface-container-highest":   "var(--tw-c-container-highest)",
        "surface-tint":                "#5b7fff",
        "surface-variant":             "var(--tw-c-surface-variant)",
        "on-surface":                  "var(--tw-c-on-surface)",
        "on-surface-variant":          "var(--tw-c-on-surface-variant)",
        "inverse-surface":             "var(--tw-c-inverse-surface)",
        "inverse-on-surface":          "var(--tw-c-inverse-on-surface)",
        "outline":                     "var(--tw-c-outline)",
        "outline-variant":             "var(--tw-c-outline-variant)",

        /* ── Accent tokens — keep hardcoded so opacity modifiers work ── */
        "primary":                     "#5b7fff",
        "on-primary":                  "#ffffff",
        "primary-container":           "#3d58b3",
        "on-primary-container":        "#e4e7ff",
        "inverse-primary":             "#5b7fff",
        "primary-fixed":               "#dce1ff",
        "primary-fixed-dim":           "#5b7fff",
        "on-primary-fixed":            "#001551",
        "on-primary-fixed-variant":    "#223f9a",
        "secondary":                   "#52b788",
        "on-secondary":                "#ffffff",
        "secondary-container":         "#2d7a57",
        "on-secondary-container":      "#97f9ae",
        "secondary-fixed":             "#95f8ad",
        "secondary-fixed-dim":         "#52b788",
        "on-secondary-fixed":          "#00210c",
        "on-secondary-fixed-variant":  "#005227",
        "tertiary":                    "#bfc7d8",
        "on-tertiary":                 "#29313e",
        "tertiary-container":          "#606877",
        "on-tertiary-container":       "#e0e8f9",
        "tertiary-fixed":              "#dbe3f4",
        "tertiary-fixed-dim":          "#bfc7d8",
        "on-tertiary-fixed":           "#141c28",
        "on-tertiary-fixed-variant":   "#3f4755",
        "error":                       "#ffb4ab",
        "on-error":                    "#690005",
        "error-container":             "#93000a",
        "on-error-container":          "#ffdad6",
      },
      fontFamily: {
        "display-xl":       ["Space Grotesk", "sans-serif"],
        "headline-lg":      ["Space Grotesk", "sans-serif"],
        "headline-md":      ["Space Grotesk", "sans-serif"],
        "body-lg":          ["Inter", "sans-serif"],
        "body-md":          ["Inter", "sans-serif"],
        "label-sm":         ["Inter", "sans-serif"],
        "editorial-italic": ["Noto Serif", "serif"],
      },
      fontSize: {
        "display-xl":        ["var(--fs-display-xl)",  { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg":       ["var(--fs-headline-lg)",  { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md":       ["var(--fs-headline-md)",  { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg":           ["var(--fs-body-lg)",  { lineHeight: "1.6", fontWeight: "400" }],
        "body-md":           ["var(--fs-body-md)",  { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm":          ["12px",  { lineHeight: "1",   letterSpacing: "0.05em", fontWeight: "600" }],
        "editorial-italic":  ["20px",  { lineHeight: "1.6", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1440px",
      },
      spacing: {
        "margin-edge": "var(--spacing-margin-edge)",
        "gutter":      "var(--spacing-gutter)",
        "section-gap": "var(--spacing-section-gap)",
        "unit":        "8px",
      },
    },
  },
  plugins: [],
}
