module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background":                  "#1a232e",
        "on-background":               "#f0f2f5",
        "surface":                     "#1a232e",
        "surface-dim":                 "#151d26",
        "surface-bright":              "#2c3846",
        "surface-container-lowest":    "#0f161d",
        "surface-container-low":       "#222c38",
        "surface-container":           "#283340",
        "surface-container-high":      "#323f4e",
        "surface-container-highest":   "#3d4b5c",
        "surface-tint":                "#5b7fff",
        "surface-variant":             "#2c3846",
        "on-surface":                  "#f0f2f5",
        "on-surface-variant":          "#a8b3c1",
        "inverse-surface":             "#f0f2f5",
        "inverse-on-surface":          "#1a232e",
        "outline":                     "#637283",
        "outline-variant":             "#404e5d",
        "primary":                     "#5b7fff",
        "on-primary":                  "#ffffff",
        "primary-container":           "#3d58b3",
        "on-primary-container":        "#e4e7ff",
        "inverse-primary":             "#5b7fff",
        "primary-fixed":               "#dce1ff",
        "primary-fixed-dim":           "#5b7fff",
        "on-primary-fixed":            "#001551",
        "on-primary-fixed-variant":    "#223f9a",
        "secondary":                   "#52b788",
        "on-secondary":                "#ffffff",
        "secondary-container":         "#2d7a57",
        "on-secondary-container":      "#97f9ae",
        "secondary-fixed":             "#95f8ad",
        "secondary-fixed-dim":         "#52b788",
        "on-secondary-fixed":          "#00210c",
        "on-secondary-fixed-variant":  "#005227",
        "tertiary":                    "#bfc7d8",
        "on-tertiary":                 "#29313e",
        "tertiary-container":          "#606877",
        "on-tertiary-container":       "#e0e8f9",
        "tertiary-fixed":              "#dbe3f4",
        "tertiary-fixed-dim":          "#bfc7d8",
        "on-tertiary-fixed":           "#141c28",
        "on-tertiary-fixed-variant":   "#3f4755",
        "error":                       "#ffb4ab",
        "on-error":                    "#690005",
        "error-container":             "#93000a",
        "on-error-container":          "#ffdad6",
      },
      fontFamily: {
        "display-xl":       ["Space Grotesk", "sans-serif"],
        "headline-lg":      ["Space Grotesk", "sans-serif"],
        "headline-md":      ["Space Grotesk", "sans-serif"],
        "body-lg":          ["Inter", "sans-serif"],
        "body-md":          ["Inter", "sans-serif"],
        "label-sm":         ["Inter", "sans-serif"],
        "editorial-italic": ["Noto Serif", "serif"],
      },
      fontSize: {
        "display-xl":        ["72px",  { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg":       ["48px",  { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md":       ["32px",  { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg":           ["18px",  { lineHeight: "1.6", fontWeight: "400" }],
        "body-md":           ["16px",  { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm":          ["12px",  { lineHeight: "1",   letterSpacing: "0.05em", fontWeight: "600" }],
        "editorial-italic":  ["20px",  { lineHeight: "1.6", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1440px",
      },
      spacing: {
        "margin-edge": "64px",
        "gutter":      "32px",
        "section-gap": "128px",
        "unit":        "8px",
      },
    },
  },
  plugins: [],
}
